### ISSUE TITLE
Sintesis_Buenas prácticas en Gestión de Proyectos

### ISSUE THREAD

**Issue by Graciela2000** [SistemasTecTlaxiaco/sintesis-Graciela2000#2]
[Sintesis_Buenas prácticas en Gestión de Proyectos.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-Graciela2000/files/7123302/Sintesis_Buenas.practicas.en.Gestion.de.Proyectos.pdf)

**Comment by Nancy2050** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
